set transaction read write; 
CREATE SCHEMA PUBLIC;

/* SQLINES DEMO *** le [dbo].[ASISTENCIA]    Script Date: 6/26/2022 4:21:43 PM ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE ASISTENCIA(
	ID int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	ID_ALUMNO int NOT NULL,
	ID_MATERIA int NOT NULL,
	FECHA Timestamp(3) NOT NULL,
	PRESENTE Boolean NULL,
PRIMARY KEY 
(
	ID 
) 
);
/* SQLINES DEMO *** le [dbo].[CONTACTOS]    Script Date: 6/26/2022 4:21:43 PM ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE CONTACTOS(
	ID int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	NOMBRE varchar(40) NULL,
	MAIL varchar(40) NULL,
	TELEFONO varchar(40) NULL,
PRIMARY KEY 
(
	ID 
) 
);
/* SQLINES DEMO *** le [dbo].[CONTENIDO]    Script Date: 6/26/2022 4:21:43 PM ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE CONTENIDO(
	ID int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	ID_MATERIA int NULL,
	UNIDAD int NULL,
	TITULO varchar(40) NULL,
	DESCRIPCION varchar(200) NULL,
PRIMARY KEY 
(
	ID 
) 
);
/* SQLINES DEMO *** le [dbo].[CUADERNO_COMUNICADOS]    Script Date: 6/26/2022 4:21:43 PM ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE CUADERNO_COMUNICADOS(
	ID int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	ID_ALUMNO int NULL,
	ID_PROFESOR int NULL,
	DESCRIPCION varchar(300) NULL,
	FECHA Timestamp(3) NULL,
PRIMARY KEY 
(
	ID 
) 
);
/* SQLINES DEMO *** le [dbo].[DESEMPEÑO]    Script Date: 6/26/2022 4:21:43 PM ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE DESEMPEÑO(
	ID int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	ID_ALUMNO int NULL,
	DESCRIPCION varchar(300) NULL,
	FECHA Timestamp(3) NULL,
PRIMARY KEY 
(
	ID 
) 
);
/* SQLINES DEMO *** le [dbo].[EVENTOS]    Script Date: 6/26/2022 4:21:43 PM ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE EVENTOS(
	ID int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	NOMBRE varchar(40) NULL,
	DESCRIPCION varchar(300) NULL,
	FECHA Timestamp(3) NULL,
PRIMARY KEY 
(
	ID 
) 
);
/* SQLINES DEMO *** le [dbo].[HIJOS]    Script Date: 6/26/2022 4:21:43 PM ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE HIJOS(
	ID int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	ID_PADRE int NOT NULL,
	ID_HIJO int NOT NULL,
PRIMARY KEY 
(
	ID 
) 
);
/* SQLINES DEMO *** le [dbo].[INTEGRANTES_EVENTOS]    Script Date: 6/26/2022 4:21:43 PM ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE INTEGRANTES_EVENTOS(
	ID int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	ID_EVENTO int NOT NULL,
	ID_USUARIO int NOT NULL,
PRIMARY KEY 
(
	ID 
) 
);
/* SQLINES DEMO *** le [dbo].[INTEGRANTES_MATERIAS]    Script Date: 6/26/2022 4:21:43 PM ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE INTEGRANTES_MATERIAS(
	ID int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	ID_MATERIA int NOT NULL,
	ID_USUARIO int NOT NULL,
PRIMARY KEY 
(
	ID 
) 
);
/* SQLINES DEMO *** le [dbo].[MATERIAS]    Script Date: 6/26/2022 4:21:43 PM ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE MATERIAS(
	ID int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	NOMBRE varchar(40) NULL,
	CURSO varchar(40) NULL,
PRIMARY KEY 
(
	ID 
) 
);
/* SQLINES DEMO *** le [dbo].[PAGOS]    Script Date: 6/26/2022 4:21:43 PM ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE PAGOS(
	ID int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	ID_ALUMNO int NULL,
	CONCEPTO varchar(40) NULL,
	MONTO Double precision NULL,
	PAGADO Boolean NULL,
	VENCIMIENTO Timestamp(3) NULL,
PRIMARY KEY 
(
	ID 
) 
);
/* SQLINES DEMO *** le [dbo].[TAREAS]    Script Date: 6/26/2022 4:21:43 PM ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE TAREAS(
	ID int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	TITULO varchar(40) NULL,
	DESCRIPCION varchar(300) NULL,
	FECHA_ENTREGA Timestamp(3) NULL,
	ENTREGADO Boolean NULL,
	CALIFICACION Double precision NULL,
	ID_MATERIA int NULL,
	ID_ALUMNO int NULL,
PRIMARY KEY 
(
	ID 
) 
);
/* SQLINES DEMO *** le [dbo].[USUARIOS]    Script Date: 6/26/2022 4:21:43 PM ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE USUARIOS(
	ID int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	ACTIVO Boolean NULL,
	NOMBRE varchar(40) NULL,
	APELLIDO varchar(40) NULL,
	PERFIL varchar(40) NULL,
	MAIL varchar(40) NULL,
PRIMARY KEY 
(
	ID 
) 
);
ALTER TABLE ASISTENCIA  ADD  CONSTRAINT FK_ASISTENCIA_ALUMNO FOREIGN KEY(ID_ALUMNO)
REFERENCES USUARIOS (ID);
 
ALTER TABLE ASISTENCIA VALIDATE CONSTRAINT FK_ASISTENCIA_ALUMNO;
 
ALTER TABLE ASISTENCIA  ADD  CONSTRAINT FK_ASISTENCIA_MATERIA FOREIGN KEY(ID_MATERIA)
REFERENCES MATERIAS (ID);
 
ALTER TABLE ASISTENCIA VALIDATE CONSTRAINT FK_ASISTENCIA_MATERIA;
 
ALTER TABLE CONTENIDO  ADD  CONSTRAINT FK_CONTENIDO_MATERIA FOREIGN KEY(ID_MATERIA)
REFERENCES MATERIAS (ID);
 
ALTER TABLE CONTENIDO VALIDATE CONSTRAINT FK_CONTENIDO_MATERIA;
 
ALTER TABLE CUADERNO_COMUNICADOS  ADD  CONSTRAINT FK_CUADERNO_ALUMNO FOREIGN KEY(ID_ALUMNO)
REFERENCES USUARIOS (ID);
 
ALTER TABLE CUADERNO_COMUNICADOS VALIDATE CONSTRAINT FK_CUADERNO_ALUMNO;
 
ALTER TABLE CUADERNO_COMUNICADOS  ADD  CONSTRAINT FK_CUADERNO_PROFESOR FOREIGN KEY(ID_PROFESOR)
REFERENCES USUARIOS (ID);
 
ALTER TABLE CUADERNO_COMUNICADOS VALIDATE CONSTRAINT FK_CUADERNO_PROFESOR;
 
ALTER TABLE DESEMPEÑO  ADD  CONSTRAINT FK_DESEMPEÑO_ALUMNO FOREIGN KEY(ID_ALUMNO)
REFERENCES USUARIOS (ID);
 
ALTER TABLE DESEMPEÑO VALIDATE CONSTRAINT FK_DESEMPEÑO_ALUMNO;
 
ALTER TABLE HIJOS  ADD  CONSTRAINT FK_HIJOS_HIJO FOREIGN KEY(ID_HIJO)
REFERENCES USUARIOS (ID);
 
ALTER TABLE HIJOS VALIDATE CONSTRAINT FK_HIJOS_HIJO;
 
ALTER TABLE HIJOS  ADD  CONSTRAINT FK_HIJOS_PADRE FOREIGN KEY(ID_PADRE)
REFERENCES USUARIOS (ID);
 
ALTER TABLE HIJOS VALIDATE CONSTRAINT FK_HIJOS_PADRE;
 
ALTER TABLE INTEGRANTES_EVENTOS  ADD  CONSTRAINT FK_EVENTOS_EVENTO FOREIGN KEY(ID_EVENTO)
REFERENCES EVENTOS (ID);
 
ALTER TABLE INTEGRANTES_EVENTOS VALIDATE CONSTRAINT FK_EVENTOS_EVENTO;
 
ALTER TABLE INTEGRANTES_EVENTOS  ADD  CONSTRAINT FK_EVENTOS_USUARIO FOREIGN KEY(ID_USUARIO)
REFERENCES USUARIOS (ID);
 
ALTER TABLE INTEGRANTES_EVENTOS VALIDATE CONSTRAINT FK_EVENTOS_USUARIO;
 
ALTER TABLE INTEGRANTES_MATERIAS  ADD  CONSTRAINT FK_MATERIAS_MATERIA FOREIGN KEY(ID_MATERIA)
REFERENCES MATERIAS (ID);
 
ALTER TABLE INTEGRANTES_MATERIAS VALIDATE CONSTRAINT FK_MATERIAS_MATERIA;
 
ALTER TABLE INTEGRANTES_MATERIAS  ADD  CONSTRAINT FK_MATERIAS_USUARIO FOREIGN KEY(ID_USUARIO)
REFERENCES USUARIOS (ID);
 
ALTER TABLE INTEGRANTES_MATERIAS VALIDATE CONSTRAINT FK_MATERIAS_USUARIO;
 
ALTER TABLE PAGOS  ADD  CONSTRAINT FK_PAGOS_ALUMNO FOREIGN KEY(ID_ALUMNO)
REFERENCES USUARIOS (ID);
 
ALTER TABLE PAGOS VALIDATE CONSTRAINT FK_PAGOS_ALUMNO;
 
ALTER TABLE TAREAS  ADD  CONSTRAINT FK_TAREAS_ALUMNO FOREIGN KEY(ID_ALUMNO)
REFERENCES USUARIOS (ID);
 
ALTER TABLE TAREAS VALIDATE CONSTRAINT FK_TAREAS_ALUMNO;
 
ALTER TABLE TAREAS  ADD  CONSTRAINT FK_TAREAS_MATERIA FOREIGN KEY(ID_MATERIA)
REFERENCES MATERIAS (ID);
 
ALTER TABLE TAREAS VALIDATE CONSTRAINT FK_TAREAS_MATERIA;
 
